### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by goofas** [perceptron8/babel.ext#1]
some time ago babel stop working game again is in german

**Comment by perceptron8** [comment]
omg! this extension has users! ;)

thanks for letting me know. i'll try to resolve your problem soon

**Comment by perceptron8** [comment]
fixed with e0d1983d9a1a8589fad9c03652338a6a18f33e28
if you are using Chrome or Firefox, wait for version 0.0.2
if you are using Opera, wait for 0.0.3

**Comment by goofas** [comment]
Chrome działa 😁

21.12.2017 4:23 PM "Michał Sobkiewicz" <notifications@github.com>
napisał(a):
